
-- CREATE TABLE "BANK_ACCOUNT1"
   -- (	"ID" NUMBER(19,0) NOT NULL ENABLE,
	-- "FULL_NAME" VARCHAR2(128 BYTE) NOT NULL ENABLE,
	-- "BALANCE" NUMBER NOT NULL ENABLE,
	 -- CONSTRAINT "BANK_ACCOUNT_PK1" PRIMARY KEY ("ID")

   -- );